// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrangeScout.Data;

#nullable disable

namespace StrangeScout.Migrations
{
    [DbContext(typeof(StrangeScoutContext))]
    partial class StrangeScoutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("StrangeScout.Models.Matches", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Center")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cubes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CycleTime")
                        .HasColumnType("REAL");

                    b.Property<int>("DoubleSubstation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engaged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleSubstation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
